### ISSUE TITLE
Fix issue Starting Round 1 of ROSCA

### ISSUE THREAD

**Issue by joeyurgz** [WeTrustPlatform/rosca-contracts#127]
From the ROSCA management dashboard, I clicked the 'Start ROSCA' button to begin Round 1 a broadcast the following transaction via MetaMask: https://etherscan.io/tx/0x4ae40a1752ce88cc225f0e674909e862a3d9e97232ff6b08a26c8936f34f52ca

It has been nearly 20 minutes since the tx was confirmed and I received notification emails stating Round 1 has begun and is open for contributions, but the dashboard remains the same, with only an option to 'Start ROSCA' not to contribute. Broadcasting a second tx to start the ROSCA has yielded the same result.

**Comment by morelazers** [comment]
Hey @joeyurgz, thanks for reporting this, I mistakenly pushed an update to the ROSCA which wasn't backwards compatible (adding the fee percentage).

I'm going to make sure the review process is tightened up to prevent this happening again, but in the meantime I've manually patched your ROSCA and all others affected so that you can continue testing.

**Comment by joeyurgz** [comment]
Great, thanks!
