### ISSUE TITLE
Flexible withdrawal option?

### ISSUE THREAD

**Issue by anzheng67** [WeTrustPlatform/rosca-contracts#99]
Do we want to support withdraw to a different address other than msg.sender?

**Comment by morelazers** [comment]
+1, wasn't this a feature in earlier versions of the contract?

**Comment by rmerom** [comment]
We first thought of having this feature because we were concerned with online wallet users not being able to receive funds.
Later on we realized that they participants would not be able to use online wallets because they need to issue transactions, not just send money, so we thought of dropping this feature.
If you see any other good reason why this is important to have for MVP, please let us know.

**Comment by morelazers** [comment]
Sounds good to me, I've updated the frontend in one of the PRs, if it doesn't get merged I'll make another.

**Comment by anzheng67** [comment]
fair enough!  This would not affect the user experience much so I am closing this
